[package]
name = "wasmmodule"
version = "0.1.0"
authors = ["rev1 rev1engine@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.71"
mogwai = "0.4.0"