version: 2
jobs:
  build:
    docker:
      - image: rust:1.50.0-alpine3.12
    steps:
    	- checkout
    	#- run:
      #    name: "TargetAddWASM"
      #    command: rustup target add wasm32-unknown-unknown
      - run:
          name: "PKGConfig"
          command: apt-get -y update && apt-get -y upgrade && apt-get -y install pkg-config libssl-dev
      - run:
          name: "WASMPack"
          command: mkdir crates crates/bin && cargo install wasm-pack --root crates
      - store_artifacts:
          path: crates